version: '2.2'

services:
  openvpn:
    image: 0x022b/openvpn
    restart: on-failure
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - KILL
      - NET_ADMIN
      - NET_RAW
      - SETGID
      - SETUID
    logging:
      driver: none
    tmpfs:
      - /run:rw,nodev,noexec,nosuid,size=16m
      - /tmp:rw,nodev,noexec,nosuid,size=16m
    volumes:
      - app:/app:Z

volumes:
  app:
